<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $image = 'new_products_content_widget_grid';
?>
    <div class="block widget">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php echo $title; ?></strong>
        </div>
        <?php endif; ?>
        <div class="block-content">
            <div data-mage-init='{"slick": {"slidesToShow": 6, "slidesToScroll": 6, "dots": false, "autoplay": false, "variableWidth": false}}'>
                <?php foreach ($items as $_item): ?>
                    <a style="margin-right: 10px" href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                    </a>
                <?php endforeach ?>
            </div>
        </div>
    </div>
<?php endif;?>
